include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    require_trailing_commas: true
    avoid_redundant_argument_values: true
    unnecessary_parenthesis: true
    sort_child_properties_last: true
    use_super_parameters: true
    directives_ordering: true
